import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import {Comfortaa} from "@next/font/google";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import {ConfigProvider} from "antd";
const confortaa = Comfortaa({
  subsets: ["latin","cyrillic","cyrillic-ext"],
});
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={confortaa.className}>
    <AntdRegistry>
      <ConfigProvider theme={{
        token: {
          fontFamily: '',
          colorPrimary: '#ffa300'
        },
        components: {
          Pagination: {
            colorPrimary: '#fcb103',
            colorPrimaryHover: '#b59205',
            itemSize: 50,
            colorSplit: '#fcb103',
          },
          Modal: {
            titleFontSize: 20,
            titleColor: '#d18502',
          },
          Button: {
            defaultActiveColor: '#f2e63a',
          },
          Menu: {
            itemSelectedBg: '#fafa7d',
            itemSelectedColor: '#000000',
            activeBarWidth: 2,
          }
        },
      }}>
                {children}
      </ConfigProvider>
    </AntdRegistry>
    </body>
    </html>
  );
}
