import type { Metadata } from "next";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import ProductIcon from "../../../public/products-svgrepo-com.svg";
import UsersIcon from "../../../public/users-svgrepo-com.svg";
import DeliveryIcon from "../../../public/fast-food-truck-truck-svgrepo-com.svg";
import CartIcon from "../../../public/cart-shopping-svgrepo-com.svg";
import ExistIcon from "../../../public/exit-svgrepo-com.svg";
import Image from "next/image";
import React from "react";
import DashboardSlider from "@/components/DashboardSlider";
import {Header, Content} from "antd/es/layout/layout";
import {MenuItemType} from "antd/es/menu/hooks/useItems";
import Link from "next/link";
import {ConfigProvider, Dropdown, Layout} from 'antd';
import AdminLogoDropDown from "@/components/Admin_logoDropDown";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const items :MenuItemType[]  = [{src: ProductIcon , title : "Products", hrefPage: "products"} , {src: UsersIcon , title: "Users",  hrefPage: "user"} , {src : DeliveryIcon, title: "Delivery",  hrefPage: "delivery"}, {src: CartIcon, title: "Cart",  hrefPage: "cart"} ].map(
      (item, index) => ({
        key: String(index + 1),
        icon: <div><Image src={item.src} width={20} height={20} alt={item.title}/></div>,
        label: <Link href={`${item.hrefPage}`}>{item.title}</Link>,
      }),
  );
  const exitMenuItem = {src: ExistIcon, title: "Exit"}
  items.push({
    key: String(items.length + 1),
    icon: <div><Image src={exitMenuItem.src} width={20} height={20} alt={exitMenuItem.title}/></div>,
    label: <button>{exitMenuItem.title}</button>,
  })
  return (
        <Layout>
        <DashboardSlider items={items}/>
          <Layout>
            {/*<Header style={{ padding: 0, background: "red", height:  90,zIndex: 998}} className="sticky top-0" />*/}
            <Header style={{ padding: 27, background: "red", height:  75,zIndex: 998, backgroundColor: "rgb(253,253,253)"}} className="sticky top-0 flex justify-end">
              <div className="flex flex-row items-center mr-10">
                <Dropdown menu={{ items }} trigger={['click']}>
                  <AdminLogoDropDown></AdminLogoDropDown>
                </Dropdown>
              </div>
            </Header>
            <Content style={{ margin: '24px 16px 0', zIndex: 950 }}>
              <div
                  style={{
                    padding: 24,
                    minHeight: 360,
                    background: "white",
                    borderRadius: 2,
                  }}
              >
                {children}
              </div>
            </Content>
          </Layout>
        </Layout>
  );
}
